// export default [
//   {
//     id: 1,
//     name: "Bertie Yates",
//     age: 29,
//     image: "https://www.course-api.com/images/people/person-1.jpeg",
//   },
//   {
//     id: 2,
//     name: "Hester Hogan",
//     age: 32,
//     image: "https://www.course-api.com/images/people/person-2.jpeg",
//   },
//   {
//     id: 3,
//     name: "Larry Little",
//     age: 36,
//     image: "https://www.course-api.com/images/people/person-3.jpeg",
//   },
//   {
//     id: 4,
//     name: "Sean Walsh",
//     age: 34,
//     image: "https://www.course-api.com/images/people/person-4.jpeg",
//   },
//   {
//     id: 5,
//     name: "Lola Gardner",
//     age: 29,
//     image: "https://www.course-api.com/images/people/person-5.jpeg",
//   },
// ];

//----------------------------
import image1 from "./assets/image/productSlider/1.jpg";
export default [
  {
    id: 1,
    name: "iPhone 13 Pro",
    brand: "اپل",
    CPU: "AM32x",
    OS: "IOS",
    RAM: 6,
    camera_front: 32,
    camera_back: 64,
    ROM: 64,
    number: 5,
    color: ["RED", "GREEN", "BLUE"],
    image: image1,
    price: 12000000,
    date: new Date(2024, 11, 17),
    buyNumber: 23,
    favorite: 76,
    view: 43,
  },
  {
    id: 2,
    name: "Samsung Galaxy S21",
    brand: "سامسونگ",
    CPU: "Exynos 2100",
    OS: "Android",
    RAM: 8,
    camera_front: 40,
    camera_back: 108,
    ROM: 128,
    number: 10,
    color: ["BLACK", "SILVER", "VIOLET"],
    image: image1,
    price: 76000000,
    date: new Date(2024, 9, 17),
    buyNumber: 156,
    favorite: 2234,
    view: 1237,
  },
  {
    id: 3,
    name: "Huawei P40 Pro",
    brand: "هواوی",
    CPU: "Kirin 990",
    OS: "Android",
    RAM: 8,
    camera_front: 32,
    camera_back: 50,
    ROM: 256,
    number: 7,
    color: ["SILVER", "GOLD", "WHITE"],
    image: image1,
    price: 36000000,
    date: new Date(2024, 7, 17),
    buyNumber: 85,
    favorite: 88,
    view: 2234,
  },
  {
    id: 4,
    name: "Nokia 9 PureView",
    brand: "نوکیا",
    CPU: "Snapdragon 845",
    OS: "Android",
    RAM: 6,
    camera_front: 20,
    camera_back: 60,
    ROM: 128,
    number: 3,
    color: ["BLUE", "BLACK", "WHITE"],
    image: image1,
    price: 23000000,
    date: new Date(2024, 6, 17),
    buyNumber: 67,
    favorite: 65,
    view: 334,
  },
  {
    id: 5,
    name: "Xiaomi Mi 11",
    brand: "شیاومی",
    CPU: "Snapdragon 888",
    OS: "Android",
    RAM: 8,
    camera_front: 20,
    camera_back: 108,
    ROM: 256,
    number: 9,
    color: ["BLACK", "BLUE", "PURPLE"],
    image: image1,
    price: 45000000,
    date: new Date(2024, 3, 17),
    buyNumber: 98,
    favorite: 776,
    view: 445,
  },
];

// [
//   {
//     id: 1,
//     name: "iPhone 13 Pro",
//     brand: "اپل",
//     CPU: "AM32x",
//     OS: "IOS",
//     RAM: 6,
//     camera_front: 32,
//     camera_back: 64,
//     ROM: 64,
//     number: 5,
//     color: ["RED", "GREEN", "BLUE"],
//     image: null,
//   },
//   {
//     id: 2,
//     name: "Samsung Galaxy S21",
//     brand: "سامسونگ",
//     CPU: "Exynos 2100",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 40,
//     camera_back: 108,
//     ROM: 128,
//     number: 10,
//     color: ["BLACK", "SILVER", "VIOLET"],
//     image: null,
//   },
//   {
//     id: 3,
//     name: "Huawei P40 Pro",
//     brand: "هواوی",
//     CPU: "Kirin 990",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 32,
//     camera_back: 50,
//     ROM: 256,
//     number: 7,
//     color: ["SILVER", "GOLD", "WHITE"],
//     image: null,
//   },
//   {
//     id: 4,
//     name: "Nokia 9 PureView",
//     brand: "نوکیا",
//     CPU: "Snapdragon 845",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 20,
//     camera_back: 60,
//     ROM: 128,
//     number: 3,
//     color: ["BLUE", "BLACK", "WHITE"],
//     image: null,
//   },
//   {
//     id: 5,
//     name: "Xiaomi Mi 11",
//     brand: "شیاومی",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 20,
//     camera_back: 108,
//     ROM: 256,
//     number: 9,
//     color: ["BLACK", "BLUE", "PURPLE"],
//     image: null,
//   },
//   {
//     id: 6,
//     name: "Redmi Note 10",
//     brand: "شیائومی",
//     CPU: "Snapdragon 678",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 13,
//     camera_back: 48,
//     ROM: 128,
//     number: 6,
//     color: ["GRAY", "GREEN", "WHITE"],
//     image: null,
//   },
//   {
//     id: 7,
//     name: "Google Pixel 6",
//     brand: "گوگل",
//     CPU: "Tensor",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 12,
//     camera_back: 50,
//     ROM: 128,
//     number: 4,
//     color: ["BLACK", "WHITE", "ORANGE"],
//     image: null,
//   },
//   {
//     id: 8,
//     name: "OnePlus 9 Pro",
//     brand: "وان‌پلاس",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 12,
//     camera_front: 16,
//     camera_back: 48,
//     ROM: 256,
//     number: 8,
//     color: ["BLACK", "SILVER", "GREEN"],
//     image: null,
//   },
//   {
//     id: 9,
//     name: "Sony Xperia 1 III",
//     brand: "سونی",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 12,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 256,
//     number: 5,
//     color: ["BLACK", "WHITE", "PURPLE"],
//     image: null,
//   },
//   {
//     id: 10,
//     name: "LG Velvet",
//     brand: "ال‌جی",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 16,
//     camera_back: 48,
//     ROM: 128,
//     number: 2,
//     color: ["SILVER", "BLACK", "GREEN"],
//     image: null,
//   },

//   {
//     id: 11,
//     name: "iPhone 13",
//     brand: "اپل",
//     CPU: "A15 Bionic",
//     OS: "iOS",
//     RAM: 6,
//     camera_front: 12,
//     camera_back: 12,
//     ROM: 128,
//     number: 15,
//     color: ["BLACK", "BLUE", "PINK"],
//     image: null,
//   },
//   {
//     id: 12,
//     name: "Samsung Galaxy Z Fold 3",
//     brand: "سامسونگ",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 12,
//     camera_front: 10,
//     camera_back: 12,
//     ROM: 256,
//     number: 8,
//     color: ["BLACK", "GREEN", "SILVER"],
//     image: null,
//   },
//   {
//     id: 13,
//     name: "Huawei Mate 40 Pro",
//     brand: "هواوی",
//     CPU: "Kirin 9000",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 13,
//     camera_back: 50,
//     ROM: 256,
//     number: 6,
//     color: ["SILVER", "BLACK", "GREEN"],
//     image: null,
//   },
//   {
//     id: 14,
//     name: "Nokia 8.3",
//     brand: "نوکیا",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 24,
//     camera_back: 64,
//     ROM: 128,
//     number: 4,
//     color: ["BLUE", "WHITE", "BLACK"],
//     image: null,
//   },
//   {
//     id: 15,
//     name: "Xiaomi Redmi Note 11",
//     brand: "شیاومی",
//     CPU: "Snapdragon 680",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 16,
//     camera_back: 64,
//     ROM: 128,
//     number: 10,
//     color: ["GRAY", "GREEN", "BLUE"],
//     image: null,
//   },
//   {
//     id: 16,
//     name: "Redmi K40",
//     brand: "شیائومی",
//     CPU: "Snapdragon 870",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 20,
//     camera_back: 48,
//     ROM: 128,
//     number: 7,
//     color: ["BLACK", "WHITE", "BLUE"],
//     image: null,
//   },
//   {
//     id: 17,
//     name: "Google Pixel 5a",
//     brand: "گوگل",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 128,
//     number: 9,
//     color: ["BLACK", "WHITE", "GREEN"],
//     image: null,
//   },
//   {
//     id: 18,
//     name: "OnePlus 9",
//     brand: "وان‌پلاس",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 16,
//     camera_back: 48,
//     ROM: 256,
//     number: 5,
//     color: ["BLACK", "SILVER", "PURPLE"],
//     image: null,
//   },
//   {
//     id: 19,
//     name: "Sony Xperia 5 II",
//     brand: "سونی",
//     CPU: "Snapdragon 865",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 256,
//     number: 3,
//     color: ["BLACK", "BLUE", "RED"],
//     image: null,
//   },
//   {
//     id: 20,
//     name: "LG Wing",
//     brand: "ال‌جی",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 32,
//     camera_back: 64,
//     ROM: 256,
//     number: 6,
//     color: ["BLACK", "WHITE", "AURORA"],
//     image: null,
//   },
//   {
//     id: 11,
//     name: "iPhone 13",
//     brand: "اپل",
//     CPU: "A15 Bionic",
//     OS: "iOS",
//     RAM: 6,
//     camera_front: 12,
//     camera_back: 12,
//     ROM: 128,
//     number: 15,
//     color: ["BLACK", "BLUE", "PINK"],
//     image: null,
//   },
//   {
//     id: 12,
//     name: "Samsung Galaxy Z Fold 3",
//     brand: "سامسونگ",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 12,
//     camera_front: 10,
//     camera_back: 12,
//     ROM: 256,
//     number: 8,
//     color: ["BLACK", "GREEN", "SILVER"],
//     image: null,
//   },
//   {
//     id: 13,
//     name: "Huawei Mate 40 Pro",
//     brand: "هواوی",
//     CPU: "Kirin 9000",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 13,
//     camera_back: 50,
//     ROM: 256,
//     number: 6,
//     color: ["SILVER", "BLACK", "GREEN"],
//     image: null,
//   },
//   {
//     id: 14,
//     name: "Nokia 8.3",
//     brand: "نوکیا",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 24,
//     camera_back: 64,
//     ROM: 128,
//     number: 4,
//     color: ["BLUE", "WHITE", "BLACK"],
//     image: null,
//   },
//   {
//     id: 15,
//     name: "Xiaomi Redmi Note 11",
//     brand: "شیاومی",
//     CPU: "Snapdragon 680",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 16,
//     camera_back: 64,
//     ROM: 128,
//     number: 10,
//     color: ["GRAY", "GREEN", "BLUE"],
//     image: null,
//   },
//   {
//     id: 16,
//     name: "Redmi K40",
//     brand: "شیائومی",
//     CPU: "Snapdragon 870",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 20,
//     camera_back: 48,
//     ROM: 128,
//     number: 7,
//     color: ["BLACK", "WHITE", "BLUE"],
//     image: null,
//   },
//   {
//     id: 17,
//     name: "Google Pixel 5a",
//     brand: "گوگل",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 128,
//     number: 9,
//     color: ["BLACK", "WHITE", "GREEN"],
//     image: null,
//   },
//   {
//     id: 18,
//     name: "OnePlus 9",
//     brand: "وان‌پلاس",
//     CPU: "Snapdragon 888",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 16,
//     camera_back: 48,
//     ROM: 256,
//     number: 5,
//     color: ["BLACK", "SILVER", "PURPLE"],
//     image: null,
//   },
//   {
//     id: 19,
//     name: "Sony Xperia 5 II",
//     brand: "سونی",
//     CPU: "Snapdragon 865",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 256,
//     number: 3,
//     color: ["BLACK", "BLUE", "RED"],
//     image: null,
//   },
//   {
//     id: 20,
//     name: "LG Wing",
//     brand: "ال‌جی",
//     CPU: "Snapdragon 765G",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 32,
//     camera_back: 64,
//     ROM: 256,
//     number: 6,
//     color: ["BLACK", "WHITE", "AURORA"],
//     image: null,
//   },
//   {
//     id: 21,
//     name: "iPhone 12",
//     brand: "اپل",
//     CPU: "A14 Bionic",
//     OS: "iOS",
//     RAM: 4,
//     camera_front: 12,
//     camera_back: 12,
//     ROM: 256,
//     number: 12,
//     color: ["BLACK", "WHITE", "RED"],
//     image: null,
//   },
//   {
//     id: 22,
//     name: "Samsung Galaxy A52",
//     brand: "سامسونگ",
//     CPU: "Snapdragon 720G",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 32,
//     camera_back: 64,
//     ROM: 128,
//     number: 10,
//     color: ["BLACK", "BLUE", "VIOLET"],
//     image: null,
//   },
//   {
//     id: 23,
//     name: "Huawei Nova 8",
//     brand: "هواوی",
//     CPU: "Kirin 985",
//     OS: "Android",
//     RAM: 8,
//     camera_front: 32,
//     camera_back: 64,
//     ROM: 128,
//     number: 8,
//     color: ["BLACK", "SILVER", "BLUE"],
//     image: null,
//   },
//   {
//     id: 24,
//     name: "Nokia X20",
//     brand: "نوکیا",
//     CPU: "Snapdragon 480",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 32,
//     camera_back: 64,
//     ROM: 128,
//     number: 5,
//     color: ["BLUE", "WHITE", "SAND"],
//     image: null,
//   },
//   {
//     id: 25,
//     name: "Xiaomi Redmi Note 10 Pro",
//     brand: "شیاومی",
//     CPU: "Snapdragon 732G",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 16,
//     camera_back: 108,
//     ROM: 128,
//     number: 9,
//     color: ["BRONZE", "GRAY", "BLUE"],
//     image: null,
//   },
//   {
//     id: 26,
//     name: "Redmi 9",
//     brand: "شیائومی",
//     CPU: "MediaTek Helio G80",
//     OS: "Android",
//     RAM: 4,
//     camera_front: 8,
//     camera_back: 13,
//     ROM: 64,
//     number: 7,
//     color: ["GRAY", "GREEN", "PURPLE"],
//     image: null,
//   },
//   {
//     id: 27,
//     name: "Google Pixel 4a",
//     brand: "گوگل",
//     CPU: "Snapdragon 730G",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 128,
//     number: 6,
//     color: ["BLACK", "WHITE", "ORANGE"],
//     image: null,
//   },
//   {
//     id: 28,
//     name: "OnePlus Nord N200",
//     brand: "وان‌پلاس",
//     CPU: "Snapdragon 480",
//     OS: "Android",
//     RAM: 4,
//     camera_front: 16,
//     camera_back: 48,
//     ROM: 64,
//     number: 4,
//     color: ["BLUE", "GRAY", "SILVER"],
//     image: null,
//   },
//   {
//     id: 29,
//     name: "Sony Xperia 10 III",
//     brand: "سونی",
//     CPU: "Snapdragon 690",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 8,
//     camera_back: 12,
//     ROM: 128,
//     number: 3,
//     color: ["BLACK", "WHITE", "BLUE"],
//     image: null,
//   },
//   {
//     id: 30,
//     name: "LG K92 5G",
//     brand: "ال‌جی",
//     CPU: "Snapdragon 690",
//     OS: "Android",
//     RAM: 6,
//     camera_front: 16,
//     camera_back: 64,
//     ROM: 128,
//     number: 2,
//     color: ["TITAN", "SILVER", "TITANIUM"],
//     image: null,
//   },
// ];
